"""
This type stub file was generated by pyright.
"""

from boto3_type_annotations.dynamodb.client import Client
from boto3_type_annotations.dynamodb.service_resource import ServiceResource, Table, tables

