"""
This type stub file was generated by pyright.
"""

from typing import Dict
from botocore.waiter import Waiter

class TableExists(Waiter):
    def wait(self, TableName: str, WaiterConfig: Dict = ...):
        ...
    


class TableNotExists(Waiter):
    def wait(self, TableName: str, WaiterConfig: Dict = ...):
        ...
    


